# Generated by Django 2.2.2 on 2019-07-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationAdd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='Likes',
            field=models.IntegerField(default=0),
        ),
    ]
