# Generated by Django 2.2.2 on 2019-07-26 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationAdd', '0002_publication_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='Likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
