# Generated by Django 2.2.3 on 2019-07-28 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationAdd', '0004_auto_20190726_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='rubr',
            new_name='rubric',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='DelayedPosting',
        ),
        migrations.AddField(
            model_name='publication',
            name='DateOfPublic',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 28, 19, 37, 20, 489985)),
        ),
    ]
