# Generated by Django 2.2.3 on 2019-07-29 20:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PublicationAdd', '0006_auto_20190729_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='DateOfPublic',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 29, 23, 46, 34, 353089)),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(default=None, to='PublicationAdd.Tag'),
        ),
    ]
